export const getCurrencyName = (code: string): string => {
  const map: Record<string, string> = {
    btc: 'Bitcoin',
    eth: 'Ethereum',
    ltc: 'Litecoin',
    bch: 'Bitcoin Cash',
    bnb: 'Binance Coin',
    eos: 'EOS',
    xrp: 'Ripple',
    xlm: 'Stellar',
    link: 'Chainlink',
    dot: 'Polkadot',
    yfi: 'Yearn.finance',
    sol: 'Solana',
    bits: 'Bits',
    sats: 'Satoshis',
    xdr: 'Derechos Especiales de Giro',
    xag: 'Plata',
    xau: 'Oro',
    usd: 'Dólar estadounidense',
    aed: 'Dirham de Emiratos Árabes',
    ars: 'Peso argentino',
    aud: 'Dólar australiano',
    bdt: 'Taka bangladesí',
    bhd: 'Dinar bahreiní',
    bmd: 'Dólar bermudeño',
    brl: 'Real brasileño',
    cad: 'Dólar canadiense',
    chf: 'Franco suizo',
    clp: 'Peso chileno',
    cny: 'Yuan chino',
    czk: 'Corona checa',
    dkk: 'Corona danesa',
    eur: 'Euro',
    gbp: 'Libra esterlina',
    gel: 'Lari georgiano',
    hkd: 'Dólar hongkonés',
    huf: 'Florín húngaro',
    idr: 'Rupia indonesia',
    ils: 'Nuevo shéquel israelí',
    inr: 'Rupia india',
    jpy: 'Yen japonés',
    krw: 'Won surcoreano',
    kwd: 'Dinar kuwaití',
    lkr: 'Rupia de Sri Lanka',
    mmk: 'Kyat birmano',
    mxn: 'Peso mexicano',
    myr: 'Ringgit malayo',
    ngn: 'Naira nigeriana',
    nok: 'Corona noruega',
    nzd: 'Dólar neozelandés',
    php: 'Peso filipino',
    pkr: 'Rupia pakistaní',
    pln: 'Zloty polaco',
    rub: 'Rublo ruso',
    sar: 'Riyal saudí',
    sek: 'Corona sueca',
    sgd: 'Dólar singapurense',
    thb: 'Baht tailandés',
    try: 'Lira turca',
    twd: 'Dólar taiwanés',
    uah: 'Grivna ucraniana',
    vef: 'Bolívar venezolano',
    vnd: 'Dong vietnamita',
    zar: 'Rand sudafricano',
  };

  return map[code.toLowerCase()] ?? code.toUpperCase();
};

export const getFlag = (code: string): string => {
  const map: Record<string, string> = {
    usd: '🇺🇸',
    aed: '🇦🇪',
    ars: '🇦🇷',
    aud: '🇦🇺',
    bdt: '🇧🇩',
    bhd: '🇧🇭',
    bmd: '🇧🇲',
    brl: '🇧🇷',
    cad: '🇨🇦',
    chf: '🇨🇭',
    clp: '🇨🇱',
    cny: '🇨🇳',
    czk: '🇨🇿',
    dkk: '🇩🇰',
    eur: '🇪🇺',
    gbp: '🇬🇧',
    gel: '🇬🇪',
    hkd: '🇭🇰',
    huf: '🇭🇺',
    idr: '🇮🇩',
    ils: '🇮🇱',
    inr: '🇮🇳',
    jpy: '🇯🇵',
    krw: '🇰🇷',
    kwd: '🇰🇼',
    lkr: '🇱🇰',
    mmk: '🇲🇲',
    mxn: '🇲🇽',
    myr: '🇲🇾',
    ngn: '🇳🇬',
    nok: '🇳🇴',
    nzd: '🇳🇿',
    php: '🇵🇭',
    pkr: '🇵🇰',
    pln: '🇵🇱',
    rub: '🇷🇺',
    sar: '🇸🇦',
    sek: '🇸🇪',
    sgd: '🇸🇬',
    thb: '🇹🇭',
    try: '🇹🇷',
    twd: '🇹🇼',
    uah: '🇺🇦',
    vef: '🇻🇪',
    vnd: '🇻🇳',
    zar: '🇿🇦',
    btc: '₿',
    eth: 'Ξ',
    ltc: 'Ł',
    bch: 'Ƀ',
    bnb: '🟡',
    eos: '🟠',
    xrp: '✕',
    xlm: '🌟',
    link: '🔗',
    dot: '🔴',
    yfi: '💰',
    sol: '🌞',
    xdr: '🌐',
    xag: '🥈',
    xau: '🥇',
    bits: '🧬',
    sats: '⚡',
  };

  return map[code.toLowerCase()] ?? '🏳️';
};

/** Lista blanca solo de monedas fiat con bandera */
const fiatFlags: Record<string, string> = {
  usd: '🇺🇸',
  aed: '🇦🇪',
  ars: '🇦🇷',
  aud: '🇦🇺',
  bdt: '🇧🇩',
  bhd: '🇧🇭',
  bmd: '🇧🇲',
  brl: '🇧🇷',
  cad: '🇨🇦',
  chf: '🇨🇭',
  clp: '🇨🇱',
  cny: '🇨🇳',
  czk: '🇨🇿',
  dkk: '🇩🇰',
  eur: '🇪🇺',
  gbp: '🇬🇧',
  gel: '🇬🇪',
  hkd: '🇭🇰',
  huf: '🇭🇺',
  idr: '🇮🇩',
  ils: '🇮🇱',
  inr: '🇮🇳',
  jpy: '🇯🇵',
  krw: '🇰🇷',
  kwd: '🇰🇼',
  lkr: '🇱🇰',
  mmk: '🇲🇲',
  mxn: '🇲🇽',
  myr: '🇲🇾',
  ngn: '🇳🇬',
  nok: '🇳🇴',
  nzd: '🇳🇿',
  php: '🇵🇭',
  pkr: '🇵🇰',
  pln: '🇵🇱',
  rub: '🇷🇺',
  sar: '🇸🇦',
  sek: '🇸🇪',
  sgd: '🇸🇬',
  thb: '🇹🇭',
  try: '🇹🇷',
  twd: '🇹🇼',
  uah: '🇺🇦',
  vef: '🇻🇪',
  vnd: '🇻🇳',
  zar: '🇿🇦',
};

export const getFiatFlag = (code: string): string | null => {
  return fiatFlags[code.toLowerCase()] ?? null;
};

export const FIAT_COUNTRY_CODES = new Set<string>([
  'usd',
  'aed',
  'ars',
  'aud',
  'bdt',
  'bhd',
  'bmd',
  'brl',
  'cad',
  'chf',
  'clp',
  'cny',
  'czk',
  'dkk',
  'eur',
  'gbp',
  'gel',
  'hkd',
  'huf',
  'idr',
  'ils',
  'inr',
  'jpy',
  'krw',
  'kwd',
  'lkr',
  'mmk',
  'mxn',
  'myr',
  'ngn',
  'nok',
  'nzd',
  'php',
  'pkr',
  'pln',
  'rub',
  'sar',
  'sek',
  'sgd',
  'thb',
  'try',
  'twd',
  'uah',
  'vef',
  'vnd',
  'zar',
]);

export const isFiatCountry = (code?: string): boolean =>
  !!code && FIAT_COUNTRY_CODES.has(code.toLowerCase());
